=== the-danish-national-archives/AstaTestSuites/Styx/AVID.SA.15078.1/Tables/table12/table12.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.sa.dk/xmlns/siard/1.0/schema0/table12.xsd" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.sa.dk/xmlns/siard/1.0/schema0/table12.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="table">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="row" type="rowType" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="rowType">
    <xs:sequence>
      <xs:element minOccurs="1" name="c1" type="xs:integer" />
      <xs:element minOccurs="1" name="c2" type="xs:string" />
      <xs:element minOccurs="1" name="c3" type="xs:string" />
      <xs:element minOccurs="1" name="c4" type="xs:integer" />
      <xs:element minOccurs="1" name="c5" type="xs:decimal" />
      <xs:element minOccurs="1" name="c6" type="xs:integer" />
      <xs:element minOccurs="1" name="c7" type="xs:time" />
      <xs:element minOccurs="1" name="c8" type="xs:decimal" />
      <xs:element minOccurs="1" name="c9" nillable="true" type="xs:date" />
      <xs:element minOccurs="1" name="c10" type="xs:dateTime" />
      <xs:element minOccurs="1" name="c11" nillable="true" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== the-danish-national-archives/AstaTestSuites/Styx/AVID.SA.15078.1/Tables/table12/table12.xml
<?xml version="1.0" encoding="utf-8"?>
<table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sa.dk/xmlns/siard/1.0/schema0/table12.xsd table12.xsd" xmlns="http://www.sa.dk/xmlns/siard/1.0/schema0/table12.xsd">
  <row>
    <c1>33000</c1>
    <c2>10116</c2>
    <c3>1</c3>
    <c4>77</c4>
    <c5>178.01</c5>
    <c6>81</c6>
    <c7>17:51:30</c7>
    <c8>82.81</c8>
    <c9 xsi:nil="true" />
    <c10>2001-10-31T23:51:30</c10>
    <c11 xsi:nil="true" />
  </row>
  <row>
    <c1>33001</c1>
    <c2>10116</c2>
    <c3>2</c3>
    <c4>75</c4>
    <c5>168.00</c5>
    <c6>66</c6>
    <c7>17:51:30</c7>
    <c8>65.00</c8>
    <c9>2011-11-14</c9>
    <c10>1960-02-22T20:51:32</c10>
    <c11>65.507 tegn med mellemrum. Dette er første kolonne i table 12 som indeholder felter med for lange tekstfelter over 32.767 bytes. myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversionerArkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversionerArkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversionerArkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversioner Arkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversionerArkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversionerArkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversionerArkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversionerArkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversionerArkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversionerArkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversioner Arkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversionerArkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversionerArkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversionerArkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversionerArkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversionerArkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversionerArkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversioner Arkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversionerArkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversionerArkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende arkiv. Arkiveringsversioner af bevaringsværdige kommunale og regionale data, som ikke er omfattet af afleveringspligt, skal godkendes af samme offentlige arkiv, som modtager myndighedens afleve-ringspligtige arkiveringsversionerArkiveringsversioner af statslige myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes myndigheders data skal godkendes af Rigsarkivet. Arkive-ringsversioner af kommunale og regionale myndigheders data skal godkendes af det modtagende
